### ISSUE TITLE
Add an option to define angular path

### ISSUE THREAD

**Issue by horne3754sg** [DanWahlin/Angular2-Snippets#2]
Hi Dan, 

Really love the extension, but there is one thing that I think could improve it.

Currently when you create a component it will add the path like so.

`import { Component, OnInit } from '@angular/core';`

Is it possible to add an option to we can defined the angular folder path?

That way when a component is created it would be something like this for example.

`import { Component, OnInit } from 'angular2/core';`

**Note:** I am using Angular 2 beta 17

Regards

**Comment by DanWahlin** [comment]
Appreciate the suggestion (and sorry for the delay in responding - never got an email about this issue being submitted for some reason). In this case @angular will stay as the prefix moving forward for new versions. So, I'm going to go ahead and leave that since it's officially out and the correct prefix.
